var fs = require('fs');
var js = fs.readFileSync("js.js", { encoding: 'utf8' });
var acorn = require("acorn");
var js = acorn.parseExpressionAt(js);
var js2html = require(".");
var html = js2html.js2html(js);
console.log(html.toString());
var js = js2html.html2js(html);
var escodegen = require("escodegen");
console.log(escodegen.generate(js));
